Controllers/InvoiceController.cs
using ITRoot_Task.Models;
using ITRoot_Task.Services.IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITRoot_Task.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly IUserService _userService;
        private readonly IInvoiceService _invoiceService;
        public InvoiceController(IUserService userService, IInvoiceService invoiceService)
        {
            _userService = userService;
            _invoiceService = invoiceService;
        }

        public ActionResult Index()
        {
            string username = Session["UserName"] != null ? Session["UserName"].ToString() : "";
            string role = Session["Role"] != null ? Session["Role"].ToString() : "";
            if (string.IsNullOrEmpty(username) && string.IsNullOrEmpty(role))
            {
                return RedirectToAction("LogIn","User");
            }
            return View();
        }

        [HttpPost]
        public ActionResult GetInvoices()
        {
            List<Models.Invoice> invoices = new List<Models.Invoice>();
            User user = new User();
           
            try
            {
                string username = Session["UserName"] != null ? Session["UserName"].ToString() : "";
                if (!string.IsNullOrEmpty(username))
                {
                    user = _userService.GetUserByUserName(username);
                    if (user!=null)
                    {
                        invoices = _invoiceService.GetInvoiceByUserID(user.ID);
                        return Json(invoices);
                    }
                    
                }
                
                return Json(invoices);
            }
            catch (Exception ex)
            {
            }
            return Json(invoices);
        }


        [HttpPost]
        public ActionResult AddInvoice(List<Invoice> invoices)
        {
            int result = 0;
            try
            {
                if (ModelState.IsValid)
                {
                   var currentUser = Session["UserName"] != null ? Session["UserName"].ToString() : "";
                        result = _invoiceService.AddInvoice(invoices,currentUser);
                    return Json(result);
                }
            }
            catch (Exception ex)
            {
            }
            return Json(result);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ITRoots_Task</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ITRoots_Task", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @{
                    string userName = Session["UserName"] != null ? Session["UserName"].ToString() : "";
                    if (!string.IsNullOrEmpty(userName))
                    {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "User")</li>
                            <li>@Html.ActionLink("Invoices", "Index", "Invoice")</li>
                            <li style="margin-left:600px;padding-top:15px;font-weight:700;font-size:medium" class="text-success text-capitalize text-center">@userName</li>
                            <li>@Html.ActionLink("Log Out", "LogOut", "User")</li>
                        </ul>
                    }
                    else
                    {
                        <ul></ul>
                    }
                }

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    

    <footer>
        <div class="container" style="margin-top:15%">
            <hr />
            <p>&copy; @DateTime.Now.Year - ITRoots_Task Application</p>
        </div>
        
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>